server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /users/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/cart/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.ecommerce.apigateway: DEBUG
